-- dummy visited_courses
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 6.0, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 1.4, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 2.2, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 5.4, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 1.1, 9, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 7.7, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 4.7, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 2.2, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 3.1, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 5.9, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 4.1, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 8.8, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 3.5, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 7.2, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 8.5, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 7.9, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 5.1, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 10.0, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 5.4, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 4.4, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 4.9, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 8.7, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 8.0, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 7.3, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 3.7, 10, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 8.6, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 4.2, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 4.4, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 6.2, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 9.2, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 2.8, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 3.7, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 2.2, 9, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 3.4, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 9.3, 10, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 3.5, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 7.8, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 7.0, 10, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 3.3, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 8.3, 9, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 5.6, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 7.4, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 8.0, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 3.2, 6, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 4.5, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 5.0, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 5.5, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 4.0, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 2.5, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 1.6, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 6.8, 10, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 9.1, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 7.2, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 5.0, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 4.9, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 6.9, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 9.0, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 8.1, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 7.2, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 8.9, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 1.3, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 6.8, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 8.1, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 7.0, 6, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 8.2, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 1.8, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 4.4, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 6.8, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 2.9, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 9.5, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 8.6, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 3.0, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 8.7, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 5.8, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 7.4, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 7.8, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 9.2, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 7.0, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 2, 7.8, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 4.2, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 1.8, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 2.3, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 1, 1.3, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 5.8, 6, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 5.1, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 2, 4.8, 2, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 2.6, 10, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 5.4, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 4.8, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 7.9, 3, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 3, 4.1, 9, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 4.6, 8, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 2, 3.8, 0, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 8.0, 5, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 3, 9.9, 9, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 7.3, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (1, NOW(), 1, 9.8, 1, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (2, NOW(), 1, 9.0, 4, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 5.7, 7, 'review');
INSERT INTO visited_courses(course_id, visited_at, user_id, distance, stars, review) VALUES (3, NOW(), 3, 6.5, 5, 'review');

-- dummy health infos
insert into health_infos values(null, 1, 1, 170, 60, 23, 1, 2, 2); -- 100001
insert into health_infos values(null, 2, 0, 158, 46, 27, 0, 2, 2); -- 001101
insert into health_infos values(null, 3, 1, 182, 75, 31, 0, 2, 2); -- 011001
insert into health_infos values(null, 4, 0, 164, 51, 33, 1, 2, 2); -- 000100
insert into health_infos values(null, 5, 0, 162, 53, 21, 0, 2, 2); -- 100000

-- dummy user diseases
insert into user_diseases values(null, 1, 2, now());
insert into user_diseases values(null, 1, 4, now());
insert into user_diseases values(null, 2, 1, now());
insert into user_diseases values(null, 2, 3, now());
insert into user_diseases values(null, 2, 4, now());
insert into user_diseases values(null, 3, 1, now());
insert into user_diseases values(null, 3, 5, now());
insert into user_diseases values(null, 4, 2, now());
insert into user_diseases values(null, 4, 3, now());
insert into user_diseases values(null, 5, 1, now());
insert into user_diseases values(null, 5, 2, now());
insert into user_diseases values(null, 5, 3, now());
insert into user_diseases values(null, 5, 4, now());
insert into user_diseases values(null, 5, 5, now());